"""Repository ports — the domain defines contracts; adapters implement them."""

from __future__ import annotations

from typing import Optional, Protocol

from .aggregates import ActionItem, Note, PriorityPolicy, Project, WorkItem


class NoteRepository(Protocol):
    def get_by_id(self, note_id: int, owner_id: int) -> Optional[Note]: ...

    def find_by_idempotency_key(self, owner_id: int, key: str) -> Optional[Note]: ...

    def list_capture_inbox(self, owner_id: int, limit: int) -> list[Note]: ...

    def insert(self, fields: dict) -> Note: ...

    def triage(self, fields: dict) -> Optional[Note]: ...

    def triage_to_task(self, fields: dict) -> Optional[tuple[Note, WorkItem]]: ...

    def soft_delete(
        self, note_id: int, owner_id: int, expected_updated_at: str
    ) -> Optional[Note]: ...


class ActionItemRepository(Protocol):
    def get_by_id(self, item_id: int, owner_id: int) -> Optional[ActionItem]: ...

    def list_open(self, owner_id: int, limit: int) -> list[ActionItem]: ...

    def insert(self, fields: dict) -> ActionItem: ...

    def promote(self, fields: dict) -> Optional[tuple[ActionItem, WorkItem]]: ...

    def mark_dismissed(
        self, item_id: int, owner_id: int, expected_updated_at: str
    ) -> Optional[ActionItem]: ...


class ProjectRepository(Protocol):
    def get_by_id(self, project_id: int, owner_id: int) -> Optional[Project]: ...

    def find_live_by_name(self, owner_id: int, name: str) -> Optional[Project]: ...

    def list_live(self, owner_id: int) -> list[Project]: ...

    def insert(self, fields: dict) -> Project: ...

    def update(self, fields: dict) -> Optional[Project]: ...

    def archive(
        self, project_id: int, owner_id: int, expected_updated_at: str
    ) -> Optional[Project]: ...

    def complete(
        self, project_id: int, owner_id: int, expected_updated_at: str
    ) -> Optional[Project]: ...


class WorkItemRepository(Protocol):
    def get_by_id(self, item_id: int, owner_id: int) -> Optional[WorkItem]: ...

    def find_by_action_item_id(self, action_item_id: int, owner_id: int) -> Optional[WorkItem]: ...

    def list_live_for_project(self, project_id: int, owner_id: int) -> list[WorkItem]: ...

    def list_open_commitments(self, owner_id: int) -> list[WorkItem]: ...

    def insert(self, fields: dict) -> WorkItem: ...

    def update(self, fields: dict) -> Optional[WorkItem]: ...

    def transition(self, fields: dict) -> Optional[WorkItem]: ...

    def soft_delete(
        self, item_id: int, owner_id: int, expected_updated_at: str
    ) -> Optional[WorkItem]: ...


class PriorityPolicyRepository(Protocol):
    def get_active(self, owner_id: int) -> Optional[PriorityPolicy]: ...

    def ensure_default(self, owner_id: int) -> PriorityPolicy: ...

    def update_weights(self, fields: dict) -> Optional[PriorityPolicy]: ...
