import type { EventsWebSocketEvent } from '@nova/api-contracts'
import { queryKeys } from '@/query/keys'

type InvalidationKey = readonly unknown[]

const financeInvalidations = [
  queryKeys.finance.dashboard(),
  queryKeys.finance.accounts(),
  queryKeys.finance.creditCards(),
  queryKeys.finance.statementsAll(),
  queryKeys.finance.transactions(),
  queryKeys.finance.categories(),
  queryKeys.finance.merchants(),
  queryKeys.finance.rewards(),
  queryKeys.finance.rewardsOverview(),
  queryKeys.finance.cashback(),
  queryKeys.finance.cashbackActivity(),
  queryKeys.home(),
]

export const eventInvalidationMap: Partial<Record<EventsWebSocketEvent, InvalidationKey[]>> = {
  'api.started': [queryKeys.system.status()],
  'task.created': [queryKeys.tasks(), queryKeys.home()],
  'task.updated': [queryKeys.tasks(), queryKeys.home()],
  'spending.logged': [queryKeys.spending(), queryKeys.home()],
  'finance.account.created': financeInvalidations,
  'finance.account.updated': financeInvalidations,
  'finance.account.archived': financeInvalidations,
  'finance.account.restored': financeInvalidations,
  'finance.credit_card.created': financeInvalidations,
  'finance.credit_card.updated': financeInvalidations,
  'finance.transaction.created': financeInvalidations,
  'finance.transaction.updated': financeInvalidations,
  'finance.transaction.deleted': financeInvalidations,
  'finance.transfer.created': financeInvalidations,
  'finance.card_payment.created': financeInvalidations,
  'finance.statement.created': financeInvalidations,
  'finance.statement.updated': financeInvalidations,
  'finance.statement.paid': financeInvalidations,
  'finance.category.created': financeInvalidations,
  'finance.category.updated': financeInvalidations,
  'finance.category.deleted': financeInvalidations,
  'finance.merchant.created': financeInvalidations,
  'finance.merchant.updated': financeInvalidations,
  'finance.merchant.deleted': financeInvalidations,
  'finance.cashback.earned': financeInvalidations,
  'progress.logged': [queryKeys.home()],
  'product.created': [queryKeys.products(), queryKeys.home()],
  'product.updated': [queryKeys.products(), queryKeys.home()],
  'calendar.updated': [queryKeys.calendar(), queryKeys.home()],
  'reminder.created': [queryKeys.reminders(), queryKeys.home()],
  'reminder.triggered': [queryKeys.reminders(), queryKeys.home()],
  'memory.created': [queryKeys.memories(), queryKeys.home()],
  'habit.logged': [queryKeys.home()],
  'graph.updated': [queryKeys.graph()],
  'entity_extraction.completed': [queryKeys.graph(), queryKeys.memories()],
  'reflection.completed': [queryKeys.home()],
  'pomodoro.completed': [queryKeys.home()],
}
