"""Nova's Memory service — the only module that touches nova.db.

Every other module (voice daemon, dashboard, future services) reads and
writes structured facts through this package's public functions. Nothing
outside memory/ should open a sqlite3 connection to nova.db directly.
"""

from .graph import (
    create_entity,
    delete_edge,
    delete_entity,
    entity_edges,
    find_entity,
    get_entity,
    graph_stats,
    link_entities,
    list_graph_snapshot,
    related_entities,
)
from .habits import (
    get_habits_today,
    get_latest_habit,
    get_recent_habits,
    log_habit,
)
from .health import ping_database, semantic_index_exists
from .money import (
    add_money,
    get_latest_money,
    get_money_by_id,
    get_money_since,
    get_money_totals_between,
    get_money_totals_for_date,
    get_recent_money,
)
from .products import (
    add_product,
    find_product_by_name,
    get_product_by_id,
    get_products,
    log_sale,
    ship_product,
)
from .profile import (
    get_last_profile_update,
    get_profile_observations,
    replace_profile_observations,
)
from .progress import (
    add_progress,
    get_progress_notes_for_date,
    get_progress_since,
    get_recent_progress,
)
from .reminders import (
    add_reminder,
    count_reminders,
    get_due_reminders,
    get_latest_reminder,
    get_recent_reminders,
    get_reminder_by_id,
    get_upcoming_reminders,
)
from .schema import init_db
from .semantic import (
    archive_memory,
    count_active_memories,
    count_active_memories_by_tier,
    demote_memory,
    evaluate_memory,
    forget_memory,
    list_memories,
    maintenance,
    mark_entities_extracted,
    memories_pending_entity_extraction,
    promote_memory,
    rebuild_index,
    recalculate_scores,
    recall,
    record_access,
    record_entity_extraction_attempt,
    remember,
    restore_memory,
    supersede_memory,
    touch_memory,
)
from .tasks import (
    add_task,
    complete_task,
    complete_task_by_id,
    count_open_tasks,
    find_task_by_text,
    get_all_tasks,
    get_done_task_texts_for_date,
    get_done_tasks_since,
    get_open_tasks,
    get_recent_open_tasks,
    get_recent_tasks,
    get_task_by_id,
)

__all__ = [
    "init_db",
    "ping_database",
    "semantic_index_exists",
    "add_task",
    "complete_task",
    "get_open_tasks",
    "get_all_tasks",
    "count_open_tasks",
    "get_recent_tasks",
    "get_recent_open_tasks",
    "get_done_tasks_since",
    "get_done_task_texts_for_date",
    "add_money",
    "get_recent_money",
    "get_money_since",
    "get_money_totals_between",
    "get_money_totals_for_date",
    "add_progress",
    "get_recent_progress",
    "get_progress_since",
    "get_progress_notes_for_date",
    "add_product",
    "ship_product",
    "log_sale",
    "get_products",
    "add_reminder",
    "get_due_reminders",
    "get_upcoming_reminders",
    "count_reminders",
    "get_recent_reminders",
    "log_habit",
    "get_habits_today",
    "get_recent_habits",
    "get_profile_observations",
    "get_last_profile_update",
    "replace_profile_observations",
    "create_entity",
    "get_entity",
    "find_entity",
    "delete_entity",
    "link_entities",
    "entity_edges",
    "delete_edge",
    "related_entities",
    "list_graph_snapshot",
    "graph_stats",
    "remember",
    "supersede_memory",
    "recall",
    "list_memories",
    "count_active_memories",
    "count_active_memories_by_tier",
    "rebuild_index",
    "maintenance",
    "recalculate_scores",
    "evaluate_memory",
    "promote_memory",
    "demote_memory",
    "archive_memory",
    "forget_memory",
    "restore_memory",
    "touch_memory",
    "record_access",
    "memories_pending_entity_extraction",
    "record_entity_extraction_attempt",
    "mark_entities_extracted",
]
