"""Repository interfaces — domain defines contracts, adapters implement them."""

from __future__ import annotations

from typing import Optional, Protocol

from .aggregates import (
    Account,
    Category,
    CreditCard,
    CreditCardProfile,
    Merchant,
    Statement,
    Transaction,
)


class AccountRepository(Protocol):
    def create(self, fields: dict) -> Account: ...

    def get_by_id(self, account_id: int) -> Optional[Account]: ...

    def list_live(self) -> list[Account]: ...

    def update(self, account_id: int, fields: dict) -> Optional[Account]: ...

    def archive(self, account_id: int) -> Optional[Account]: ...

    def restore(self, account_id: int) -> Optional[Account]: ...

    def count_live_transactions(self, account_id: int) -> int: ...


class CategoryRepository(Protocol):
    def create(self, name: str) -> Category: ...

    def get_by_id(self, category_id: int) -> Optional[Category]: ...

    def get_by_name(self, name: str) -> Optional[Category]: ...

    def list_live(self) -> list[Category]: ...

    def update(self, category_id: int, name: str) -> Optional[Category]: ...

    def soft_delete(self, category_id: int) -> bool: ...


class MerchantRepository(Protocol):
    def create(self, name: str) -> Merchant: ...

    def get_by_id(self, merchant_id: int) -> Optional[Merchant]: ...

    def get_by_name(self, name: str) -> Optional[Merchant]: ...

    def list_live(self) -> list[Merchant]: ...

    def update(self, merchant_id: int, name: str) -> Optional[Merchant]: ...

    def soft_delete(self, merchant_id: int) -> bool: ...


class TransactionRepository(Protocol):
    def create(self, fields: dict) -> Transaction: ...

    def get_by_id(self, transaction_id: int) -> Optional[Transaction]: ...

    def list_live(
        self,
        account_id: Optional[int] = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Transaction]: ...

    def list_by_transfer_group(self, transfer_group_id: str) -> list[Transaction]: ...

    def update(self, transaction_id: int, fields: dict) -> Optional[Transaction]: ...

    def soft_delete(self, transaction_id: int) -> bool: ...

    def soft_delete_transfer_group(self, transfer_group_id: str) -> int: ...

    def sum_by_direction(self, account_id: int, as_of: Optional[str] = None) -> tuple[int, int]: ...

    def totals_between(self, start_date: str, end_date: str) -> tuple[int, int]: ...

    def get_latest_income_expense(self, kind: str, amount_minor: int) -> Optional[Transaction]: ...

    def ensure_default_cash_account_id(self) -> int: ...


class CreditCardRepository(Protocol):
    def create(self, account_fields: dict, profile_fields: dict) -> CreditCard: ...

    def get_by_id(self, account_id: int) -> Optional[CreditCard]: ...

    def list_live(self) -> list[CreditCard]: ...

    def update_profile(self, account_id: int, fields: dict) -> Optional[CreditCardProfile]: ...


class StatementRepository(Protocol):
    def create(self, fields: dict) -> Statement: ...

    def get_by_id(self, statement_id: int) -> Optional[Statement]: ...

    def get_by_period(self, account_id: int, period_start: str) -> Optional[Statement]: ...

    def list_for_account(self, account_id: int, limit: int = 24) -> list[Statement]: ...

    def update(self, statement_id: int, fields: dict) -> Optional[Statement]: ...

    def soft_delete(self, statement_id: int) -> bool: ...

    def count_overlapping(
        self,
        account_id: int,
        period_start: str,
        period_end: str,
        exclude_id: Optional[int] = None,
    ) -> int: ...

    def count_linked_transactions(self, statement_id: int) -> int: ...

    def sum_statement_spend(self, statement_id: int) -> tuple[int, int]: ...

    def sum_spend_in_period(
        self, account_id: int, period_start: str, period_end: str
    ) -> tuple[int, int]: ...

    def sum_statement_paid(self, statement_id: int) -> int: ...
